server {
    listen 80;
    server_name mipt.impelix.dev;

    # Для верификации Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Всё остальное — редирект на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name mipt.impelix.dev;

    ssl_certificate     /etc/letsencrypt/live/mipt.impelix.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mipt.impelix.dev/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 "ok";
        add_header Content-Type text/plain;
    }

    # Проксирование запросов к бэкенду
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
